<?php

namespace AppBundle\Repository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllWithoutPublisher() {
        $qb = $this->createQueryBuilder('p')
                    ->join('p.publisher', 'pu')
                    ->orderBy('p.createdDate', 'desc')
                    ->getQuery();

        return $qb->getResult();
    }
}
