# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AdminBundle\Entity\Administrator: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        admin:
            entity:
                class: AdminBundle\Entity\Administrator
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_login:
            pattern: ^/admin/login$
            anonymous: true

        admin:
            pattern:            /admin
            anonymous:          false
            provider:       admin
            form_login:
                login_path:     admin_login
                check_path:     admin_login_check
                default_target_path: /admin
                require_previous_session: false
            logout:
                path:           admin_logout
                target:         admin_login
            remember_me:
                secret:        %secret%
                # lifetime: 1800

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/partner/restaurant, role: ROLE_RESTAURANT }